apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipeline
spec:
  project: default
  source:
    repoURL: 'https://github.com/shirodkar/rest-and-db-gitops.git'
    path: base/pipeline
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: a-pipeline
  syncPolicy:
    automated:
        prune: true
        selfHeal: true