apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: rest-and-db
spec:
  params:
    - default: rest-and-db
      name: APP_NAME
      type: string
    - default: 'https://github.com/shirodkar/rest-and-db.git'
      name: GIT_REPO
      type: string
    - name: GIT_REVISION
      type: string
      default: main
    - default: 'quay.io/rh_ee_sshirodk/rest-and-db'
      name: IMAGE_NAME
      type: string
    - default: .
      name: PATH_CONTEXT
      type: string
    - default: latest
      name: VERSION
      type: string
  tasks:
    - name: git-clone
      params:
        - name: URL
          value: $(params.GIT_REPO)
        - name: REVISION
          value: $(params.GIT_REVISION)
        - name: SUBDIRECTORY
          value: ''
        - name: DELETE_EXISTING
          value: 'true'
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: output
          workspace: workspace
    - name: s2i
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: TLS_VERIFY
          value: 'false'
        - name: CONTEXT
          value: $(params.PATH_CONTEXT)
        - name: VERSION
          value: $(params.VERSION)
      runAfter:
        - git-clone
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: s2i-java
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: source
          workspace: workspace
        - name: dockerconfig
          workspace: quaysecret
    - name: push-image-to-quay
      params:
        - name: SOURCE_IMAGE_URL
          value: 'docker://$(tasks.s2i.results.IMAGE_URL)'
        - name: DESTINATION_IMAGE_URL
          value: 'docker://quay.io/rh_ee_sshirodk/rest-and-db:$(tasks.git-clone.results.COMMIT)'
        - name: SRC_TLS_VERIFY
          value: 'true'
        - name: DEST_TLS_VERIFY
          value: 'true'
        - name: VERBOSE
          value: 'false'
        - name: ARGS
          value: ''
      runAfter:
        - s2i
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: skopeo-copy
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
  workspaces:
    - name: workspace
    - name: quaysecret
