kind: Secret
apiVersion: v1
metadata:
  name: quaysecret
  annotations:
    tekton.dev/docker-0: 'https://quay.io/'
data:
  .dockerconfigjson: eyJhdXRocyI6eyJxdWF5LmlvIjp7InVzZXJuYW1lIjoicmhfZWVfc3NoaXJvZGsiLCJwYXNzd29yZCI6InJoX2VlX3NzaGlyb2RrIiwiYXV0aCI6ImNtaGZaV1ZmYzNOb2FYSnZaR3M2Y21oZlpXVmZjM05vYVhKdlpHcz0iLCJlbWFpbCI6IiJ9fX0=
type: kubernetes.io/dockerconfigjson
