kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres
  labels:
    template: postgresql-persistent-template
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem