kind: Secret
apiVersion: v1
metadata:
  name: postgres
  labels:
    template: postgresql-persistent-template
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
data:
  database-name: cG9zdGdyZXM=
  database-password: cG9zdGdyZXM=
  database-user: cG9zdGdyZXM=
type: Opaque